# Generated by Django 6.0.6 on 2026-06-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restuarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cuisine', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
