# Generated by Django 6.0.5 on 2026-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('rollnumber', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=10)),
            ],
        ),
    ]
