# Generated by Django 6.0.7 on 2026-08-22 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIdoctorFinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfileUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='APIdoctorFinder.doctor')),
            ],
        ),
    ]
