# Generated by Django 6.0.5 on 2026-06-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EcommerceApp.category')),
            ],
        ),
    ]
